### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by MosMK** [Far0n/kaggletils#1]
First i want to thank you for sharing this code. It cleared a lot of things for me. 
I have some questions:
1- what are the ccv features in the stacking crossvalidator class?
2- you mentioned in the inquiry list competition that you calculated likelihood features using 2 loops of cv. Did you calculate the features separately or while training a model and if you could share how to incorporate it exactly using the stacker and likelhood encoder classes i would be grateful.
thanks again

**Comment by Far0n** [comment]
ccv_features are those features from the inner cv-loop. So, if you perform a k-fold cv with CrossValidator, ccv_features need to be the oof-predictions for each train/test split regarding this k-fold. 

For example, given 3 folds [A,B,C] in the outer cv-loop, the first iteration might look like:
fold 0: train = [A,B], test = [C] 
Within, we would do sth like: 
`inner_cv = CrossValidator(LikelhoodEstimator).run_cv(train=[A,B],test=[C])`
`inner_cv.oof_train` will be the feature for [A,B] and` inner_cv.oof_test` will be the feature for [C].

ccv_features can be used to pass the precomputed features of that inner cv to avoid recalculations every time, i.e. `ccv_features[0][0] = inner_cv.oof_train`,` ccv_features[1][0] = inner_cv.oof_test`. In general:
ccv_features[i][j] =feature for dataset i (0=train, 1=test, 2=probe) for fold j.

**Comment by MosMK** [comment]
Thank you so much.
